# General paths
work_dir: "/Users/jbirkin/Code/alma_stacking_pipeline/"

# File paths
cristal_tab_file: "cristal_table_sub.fits"

# Cosmology settings
cosmology: "Planck18"

# Other configurations
default_sigma: 2
output_dir: "output/"
nu_cii: 1900.53690000